language: go
go:
  - 1.11.1
install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
script:
- hack/verify-codegen.sh
- hack/verify-boilerplate.sh
- hack/verify-gofmt.sh
- make fledged-image
- make client-image
- make test
- $(go env GOPATH | awk 'BEGIN{FS=":"} {print $1}')/bin/goveralls -coverprofile=coverage.out -service=travis-ci