apiVersion: apps/v1
kind: Deployment
metadata:
  name: fledged
  namespace: kube-fledged
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fledged
  template:
    metadata:
      labels:
        app: fledged
    spec:
      containers:
      - image: senthilrch/fledged:v0.5.0
        command: ["/opt/bin/fledged"]
        args:
        - "--stderrthreshold=INFO"
        - "--image-pull-deadline-duration=5m"
        - "--image-cache-refresh-frequency=15m"
        - "--docker-client-image=senthilrch/fledged-docker-client:v0.5.0"
        - "--image-pull-policy=IfNotPresent"
        imagePullPolicy: Always
        name: fledged
      serviceAccountName: fledged


