apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fledged
  namespace: kube-fledged
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fledged
  template:
    metadata:
      labels:
        app: fledged
    spec:
      containers:
      - env:
        - name: KUBERNETES_SERVICE_HOST
          value: 192.168.44.50
        - name: KUBERNETES_SERVICE_PORT
          value: "6443"
        image: senthilrch/fledged
        command: ["/opt/bin/fledged"]
        args:
        - "--stderrthreshold=INFO"
        - "--image-pull-deadline-duration=5m"
        - "--image-cache-refresh-frequency=0s"
        - "--docker-client-image=senthilrch/fledged-docker-client:latest"
        imagePullPolicy: Always
        name: fledged
      nodeSelector:
        kubernetes.io/hostname: worker1.k8s.cis.com
      serviceAccountName: fledged


