kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fledged
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
rules:
  - apiGroups:
      - "fledged.k8s.io"
    resources:
      - imagecaches
    verbs:
      - get
      - list
      - watch
      - update      
  - apiGroups:
      - "fledged.k8s.io"
    resources:
      - imagecaches/status
    verbs:
      - patch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - list
      - watch
      - get
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - get
      - list
      - create
      - update
      - patch
  - apiGroups:
      - "batch"
    resources:
      - jobs
    verbs:
      - get
      - create
      - delete
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
      - watch
      - get    
