apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: imagecaches.fledged.k8s.io
spec:
  group: fledged.k8s.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: imagecaches
    singular: imagecache
    kind: ImageCache
    shortNames:
    - ic
