apiVersion: apps/v1
kind: Deployment
metadata:
  name: fledged
  namespace: kube-fledged
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fledged
  template:
    metadata:
      labels:
        app: fledged
    spec:
      containers:
      - env:
        - name: KUBERNETES_SERVICE_HOST
          value: 10.128.0.29
        - name: KUBERNETES_SERVICE_PORT
          value: "6443"
        image: senthilrch/fledged:v0.3.0
        command: ["/opt/bin/fledged"]
        args:
        - "--stderrthreshold=INFO"
        - "--image-pull-deadline-duration=5m"
        - "--image-cache-refresh-frequency=15m"
        - "--docker-client-image=senthilrch/fledged-docker-client:v0.3.0"
        - "--image-pull-policy=IfNotPresent"
        imagePullPolicy: Always
        name: fledged
      serviceAccountName: fledged


