---
apiVersion: fledged.k8s.io/v1alpha1
kind: ImageCache
metadata:
  name: imagecache1
  namespace: kube-fledged
spec:
  cacheSpec:
  - images:
    - nginx
  - images:
    - redis
  imagePullSecrets:
  - name: myregistrykey
