apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: kubefledged
webhooks:
  - name: validate-image-cache.kubefledged.k8s.io
    admissionReviewVersions: ["v1"]
    timeoutSeconds: 1
    failurePolicy: Fail
    sideEffects: None
    clientConfig:
      service:
        namespace: kube-fledged
        name: kubefledged-webhook-server
        path: "/validate-image-cache"
        port: 3443
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURERENDQWZTZ0F3SUJBZ0lSQU52ZlM5L0tWK3hJeEZ3blZneVNzVkl3RFFZSktvWklodmNOQVFFTEJRQXcKTHpFdE1Dc0dBMVVFQXhNa05HRXhaREUyTmprdE9XUmpaQzAwWmpoa0xXRTJPR1V0WVRoaFlXUXhNVGRtT1dSagpNQjRYRFRJd01EVXlPVEEwTlRNeE9Wb1hEVEkxTURVeU9EQTFOVE14T1Zvd0x6RXRNQ3NHQTFVRUF4TWtOR0V4ClpERTJOamt0T1dSalpDMDBaamhrTFdFMk9HVXRZVGhoWVdReE1UZG1PV1JqTUlJQklqQU5CZ2txaGtpRzl3MEIKQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBdDRNakpWQUFYakdwVkxnWmt2cEVCOEFubEdMaERHakNHYXQ5eHk0VApoc0JlbGVTeldkUlZHZVBGTW9HNERMMndGQmRoNThHUmlxNGtNMy9LdnVMNld3c3dRYzRYWHJXYXYwdjAzYVdIClFvbWRTUVFlSnJncXlYL3dxanFYVkZ2bGtoejR1UjRaaHNoekxiMEFpLzg2Vnc5cUI2cXZkNW9tbDZBSUJZVEkKTEVQcnJTbjlMb0NEb3JNMDQ5a3AxbldDMXY0OHlmSlJ5RUN4aTRGOVRZRnE1ZDcyU09tMGNtNVZDN3A5bllBVQpvTG5VWkRkc1BLdWFHNXZHaU5GSDk1VTM2aXNsekRTV09YaFZORi9TcUxOeGJDWGZsS0wwRzZLdi9YTllGc2NPCjhaR1ArZWdBSHNjMG1VMkhCc2NDcDcxRkVySG91T0dPcVlsK3pCQ0lNWktQbHdJREFRQUJveU13SVRBT0JnTlYKSFE4QkFmOEVCQU1DQWdRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQQpkNUN5WUErbCtYVy9QckErZ0ViTWdNVnVFdnRVYzF2ay81U0RVaCs0MmZlY1pyeldjaVBvMUVKaGlRWE00NzMwCmtOTHZYYkhEYldDK2VSRFo0SUhWazV6RDl1YVBpbnU5RTRJNERvVWoydm1VOXcyQnA0dldXNnJTSVJGMmFSdW8KOGhyR2RyblNGOEdSaTZGTzFoV0xsVnJzK3RjbEhxMHdiU1hhVjNTNGhKNjd6cmE4N0IyajJ6eUZ0R0Z2dU1EdAp6VUpDOFlDTXRNMUcxNCsrWUxrVXNIbGhmMzJWanRZcmtoWHVxS2N4d05ObEcxeURsa05kdjYwRFNaZUUzNmlsCjRha2s1dC90Z200RllFMXc4b0RJNFZLM2d0cjcxNkIveWVIelIxbHJpOU1BZCtZWU1ZNUZuU0tNYStOd3EzYXYKbFNDVTBkeUdUK21WQXRXa0d0VjQrZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["kubefledged.k8s.io"]
        apiVersions: ["v1alpha1"]
        resources: ["imagecaches"]
        scope: "Namespaced"