apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubefledged
  namespace: kube-fledged
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubefledged
  template:
    metadata:
      labels:
        app: kubefledged
    spec:
      containers:
      - image: senthilrch/fledged:v0.7.0
        command: ["/opt/bin/fledged"]
        args:
        - "--stderrthreshold=INFO"
        - "--image-pull-deadline-duration=5m"
        - "--image-cache-refresh-frequency=15m"
        - "--docker-client-image=senthilrch/fledged-docker-client:v0.7.0"
        - "--image-pull-policy=Always"
        imagePullPolicy: Always
        name: fledged
        env:
        - name: KUBEFLEDGED_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      serviceAccountName: kubefledged


