kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubefledged
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fledged
subjects:
- kind: ServiceAccount
  name: kubefledged
  namespace: kube-fledged
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:nodes
