name: Build multiarch

on:
  push:
    branches: [ master ]

jobs:
  build-multiarch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - run: hack/verify-codegen.sh
    - run: hack/verify-boilerplate.sh
    - run: hack/verify-gofmt.sh
    - run: hack/verify-golint.sh
    - run: hack/verify-govet.sh
    - run: make PROGRESS=plain release
