name: Build multiarch

on:
  push:
    #branches: [ master ]
    branches: [ develop ]

jobs:
  build-multiarch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Run verify scripts
      run: |
        hack/verify-codegen.sh
        hack/verify-boilerplate.sh
        hack/verify-gofmt.sh
        hack/verify-golint.sh
        hack/verify-govet.sh
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PSWD }}
    
    - name: Build and push Controller image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: build/Dockerfile.controller
        build-args: |
          GOLANG_VERSION=1.17.7
          ALPINE_VERSION=3.15.0
        platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
        push: true
        tags: docker.io/senthilrch/kubefledged-controller:v0.10.0,docker.io/senthilrch/kubefledged-controller:latest
